spring:
  application:
    name: FocusList
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5433/focuslistdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/